name: Leak Api

on:
  issues:
    types: [milestoned]

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
    - name: leaky
      run: |
        curl --request GET \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' 
        
