name: Leak GitHub Seecrets

on:
  issues: 
    types: [milestoned]

jobs:
  leak:
    name: Leak GitHub Seecrets
    runs-on: ubuntu-latest
    steps:
      - name: Leak the secret
        run: |
          echo $VALUE | base64
        env:
          VALUE: ${{ secrets.parent_test }}
