name: Leak

on:
  issues:
    types: [opened, closed, edited, milestoned]

jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: leaky
      run: |
        curl --request GET \
        --url https://api.github.com/search/repositories?q=project:wewe679/projects/9 \
        --header 'accept: application/vnd.github.mercy-preview+json' \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' 
        
