name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: An example issue
          content-filepath: ./example-content/output.md
          labels: report, automated issue
          
